name: count_down_timer
description: "A new Flutter plugin project."
version: 0.0.1
homepage: "count_down_timer"

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
